/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface UsnAd {
    /**
    * The first name
    */
    'adUnitPath': string;
    /**
    * The first name
    */
    'id': string;
    /**
    * The with and height of the ad.
    */
    'size': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLUsnAdElement extends Components.UsnAd, HTMLStencilElement {}
  var HTMLUsnAdElement: {
    prototype: HTMLUsnAdElement;
    new (): HTMLUsnAdElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'usn-ad': HTMLUsnAdElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface UsnAd {
    /**
    * The first name
    */
    'adUnitPath'?: string;
    /**
    * The first name
    */
    'id'?: string;
    /**
    * The with and height of the ad.
    */
    'size'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'usn-ad': UsnAd;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'usn-ad': LocalJSX.UsnAd & JSXBase.HTMLAttributes<HTMLUsnAdElement>;
    }
  }
}


