/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UsnAd {
    /**
    * The first name
    */
    'adId': string;
    /**
    * The ad unit name
    */
    'adUnitPath': string;
    /**
    * The width and height of the ad.
    */
    'size': string;
    /**
    * The sizeMap used for responsive behavior.
    */
    'sizeMap': string;
    /**
    * The slot targeting.
    */
    'targeting': string;
  }
  interface UsnGpt {
    /**
    * Enables SRA.
    */
    'enableSingleRequest': boolean;
    /**
    * Centers all the ads.
    */
    'setCentering': boolean;
  }
}

declare global {


  interface HTMLUsnAdElement extends Components.UsnAd, HTMLStencilElement {}
  var HTMLUsnAdElement: {
    prototype: HTMLUsnAdElement;
    new (): HTMLUsnAdElement;
  };

  interface HTMLUsnGptElement extends Components.UsnGpt, HTMLStencilElement {}
  var HTMLUsnGptElement: {
    prototype: HTMLUsnGptElement;
    new (): HTMLUsnGptElement;
  };
  interface HTMLElementTagNameMap {
    'usn-ad': HTMLUsnAdElement;
    'usn-gpt': HTMLUsnGptElement;
  }
}

declare namespace LocalJSX {
  interface UsnAd {
    /**
    * The first name
    */
    'adId'?: string;
    /**
    * The ad unit name
    */
    'adUnitPath'?: string;
    /**
    * The width and height of the ad.
    */
    'size'?: string;
    /**
    * The sizeMap used for responsive behavior.
    */
    'sizeMap'?: string;
    /**
    * The slot targeting.
    */
    'targeting'?: string;
  }
  interface UsnGpt {
    /**
    * Enables SRA.
    */
    'enableSingleRequest'?: boolean;
    /**
    * Centers all the ads.
    */
    'setCentering'?: boolean;
  }

  interface IntrinsicElements {
    'usn-ad': UsnAd;
    'usn-gpt': UsnGpt;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'usn-ad': LocalJSX.UsnAd & JSXBase.HTMLAttributes<HTMLUsnAdElement>;
      'usn-gpt': LocalJSX.UsnGpt & JSXBase.HTMLAttributes<HTMLUsnGptElement>;
    }
  }
}


