/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UsnAdManager {
    /**
    * Enables SRA.
    */
    'enableSingleRequest': boolean;
    /**
    * Centers all the ads.
    */
    'setCentering': boolean;
  }
  interface UsnDisplayAd {
    /**
    * The first name
    */
    'adId': string;
    /**
    * The ad unit name
    */
    'adUnitPath': string;
    /**
    * The width and height of the ad.
    */
    'size': string;
    /**
    * The sizeMap used for responsive behavior.
    */
    'sizeMap': string;
    /**
    * The slot targeting.
    */
    'targeting': string;
  }
}

declare global {


  interface HTMLUsnAdManagerElement extends Components.UsnAdManager, HTMLStencilElement {}
  var HTMLUsnAdManagerElement: {
    prototype: HTMLUsnAdManagerElement;
    new (): HTMLUsnAdManagerElement;
  };

  interface HTMLUsnDisplayAdElement extends Components.UsnDisplayAd, HTMLStencilElement {}
  var HTMLUsnDisplayAdElement: {
    prototype: HTMLUsnDisplayAdElement;
    new (): HTMLUsnDisplayAdElement;
  };
  interface HTMLElementTagNameMap {
    'usn-ad-manager': HTMLUsnAdManagerElement;
    'usn-display-ad': HTMLUsnDisplayAdElement;
  }
}

declare namespace LocalJSX {
  interface UsnAdManager {
    /**
    * Enables SRA.
    */
    'enableSingleRequest'?: boolean;
    /**
    * Centers all the ads.
    */
    'setCentering'?: boolean;
  }
  interface UsnDisplayAd {
    /**
    * The first name
    */
    'adId'?: string;
    /**
    * The ad unit name
    */
    'adUnitPath'?: string;
    /**
    * The width and height of the ad.
    */
    'size'?: string;
    /**
    * The sizeMap used for responsive behavior.
    */
    'sizeMap'?: string;
    /**
    * The slot targeting.
    */
    'targeting'?: string;
  }

  interface IntrinsicElements {
    'usn-ad-manager': UsnAdManager;
    'usn-display-ad': UsnDisplayAd;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'usn-ad-manager': LocalJSX.UsnAdManager & JSXBase.HTMLAttributes<HTMLUsnAdManagerElement>;
      'usn-display-ad': LocalJSX.UsnDisplayAd & JSXBase.HTMLAttributes<HTMLUsnDisplayAdElement>;
    }
  }
}


